### ISSUE TITLE
Jekyll does not start on Arch Linux

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-pages#902]
There is no package for jekyll on Arch and jekyll is part of gemfile anyway, so "[install Jekyll](https://jekyllrb.com/docs/installation/) on your local machive" before `bundle install` should not be needed anyway.

After running `bundle install` I get this error when trying to run jekyll:
```
$ bundle exec jekyll
bundler: failed to load command: jekyll (/home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/bin/jekyll)
/home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll.rb:29:in `require': cannot load such file -- json (LoadError)
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll.rb:29:in `<top (required)>'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/exe/jekyll:8:in `require'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/exe/jekyll:8:in `<top (required)>'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `load'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `<top (required)>'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `load'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:23:in `run'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/cli.rb:492:in `exec'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/cli.rb:34:in `dispatch'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/cli.rb:28:in `start'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/user/src/deltachat/deltachat-pages/vendor/bundle/ruby/3.0.0/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
	from /usr/bin/bundle:25:in `load'
	from /usr/bin/bundle:25:in `<main>'
```

It only works after running `bundle add json`.

**Comment by link2xt** [comment]
The question is why we even tell in the readme to install jekyll when `bundle install` downloads another copy of it.

**Comment by link2xt** [comment]
There is CI and `nix build` which works, I'm not going to use `bundle` myself.
